const mongoose = require('mongoose');
const { addSoftDeleteFilter } = require('../utils/softDelete');

const certificateSchema = new mongoose.Schema({
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student',
    required: [true, 'Student ID is required'],
    index: true
  },
  certificateType: {
    type: String,
    enum: ['TRANSFER_CERTIFICATE', 'CHARACTER_CERTIFICATE', 'BONAFIDE_CERTIFICATE', 'MERIT_CERTIFICATE', 'STUDY_CERTIFICATE', 'ATTENDANCE_CERTIFICATE', 'LEAVING_CERTIFICATE', 'CONDUCT_CERTIFICATE'],
    required: [true, 'Certificate type is required'],
    index: true
  },
  certificateNumber: {
    type: String,
    unique: true,
    sparse: true,
    trim: true
  },
  issueDate: {
    type: Date,
    default: Date.now,
    required: true
  },
  expiryDate: {
    type: Date
  },
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Generated by is required']
  },
  dataPayload: {
    type: mongoose.Schema.Types.Mixed,
    required: [true, 'Data payload is required']
  },
  pdfUrl: {
    type: String,
    trim: true
  },
  status: {
    type: String,
    enum: ['DRAFT', 'ISSUED', 'VERIFIED', 'CANCELLED', 'EXPIRED'],
    default: 'ISSUED'
  },
  purpose: {
    type: String,
    trim: true,
    maxlength: [500, 'Purpose cannot exceed 500 characters']
  },
  remarks: {
    type: String,
    trim: true,
    maxlength: [500, 'Remarks cannot exceed 500 characters']
  },
  verificationCode: {
    type: String,
    unique: true,
    sparse: true
  },
  isVerified: {
    type: Boolean,
    default: false
  },
  verifiedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  verifiedAt: {
    type: Date
  },
  schoolId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'School',
    required: true,
    index: true
  },
  academicSessionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'AcademicYear'
  },

  // Audit fields
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },

  // Soft delete fields
  isDeleted: {
    type: Boolean,
    default: false
  },
  deletedAt: {
    type: Date
  },
  deletedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
certificateSchema.index({ studentId: 1, certificateType: 1 });
certificateSchema.index({ certificateNumber: 1 }, { unique: true, sparse: true });
certificateSchema.index({ verificationCode: 1 }, { unique: true, sparse: true });
certificateSchema.index({ status: 1, issueDate: -1 });
certificateSchema.index({ isDeleted: 1 });

// Apply soft delete filter
addSoftDeleteFilter(certificateSchema);

// Pre-save middleware to generate certificate number
certificateSchema.pre('save', async function(next) {
  if (this.isNew && !this.certificateNumber) {
    this.certificateNumber = await this.constructor.generateCertificateNumber(this.certificateType);
  }
  if (this.isNew && !this.verificationCode) {
    this.verificationCode = await this.constructor.generateVerificationCode();
  }
  next();
});

// Virtual for certificate validity
certificateSchema.virtual('isValid').get(function() {
  if (this.status === 'CANCELLED') return false;
  if (this.status === 'EXPIRED') return false;
  if (this.expiryDate && this.expiryDate < new Date()) return false;
  return true;
});

// Virtual for formatted certificate type
certificateSchema.virtual('formattedType').get(function() {
  const formatted = {
    'TRANSFER_CERTIFICATE': 'Transfer Certificate (TC)',
    'CHARACTER_CERTIFICATE': 'Character Certificate',
    'BONAFIDE_CERTIFICATE': 'Bonafide Certificate',
    'MERIT_CERTIFICATE': 'Merit Certificate',
    'STUDY_CERTIFICATE': 'Study Certificate',
    'ATTENDANCE_CERTIFICATE': 'Attendance Certificate',
    'LEAVING_CERTIFICATE': 'Leaving Certificate',
    'CONDUCT_CERTIFICATE': 'Conduct Certificate'
  };
  return formatted[this.certificateType] || this.certificateType;
});

// Static method to generate certificate number
certificateSchema.statics.generateCertificateNumber = async function(type) {
  const date = new Date();
  const year = date.getFullYear();
  const prefix = {
    'TRANSFER_CERTIFICATE': 'TC',
    'CHARACTER_CERTIFICATE': 'CC',
    'BONAFIDE_CERTIFICATE': 'BC',
    'MERIT_CERTIFICATE': 'MC',
    'STUDY_CERTIFICATE': 'SC',
    'ATTENDANCE_CERTIFICATE': 'AC',
    'LEAVING_CERTIFICATE': 'LC',
    'CONDUCT_CERTIFICATE': 'CON'
  }[type] || 'CERT';

  // Find count of certificates this year for sequential number
  const startOfYear = new Date(year, 0, 1);
  const endOfYear = new Date(year + 1, 0, 1);

  const count = await this.countDocuments({
    certificateType: type,
    createdAt: { $gte: startOfYear, $lt: endOfYear }
  });

  const sequential = String(count + 1).padStart(5, '0');
  return `${prefix}-${year}-${sequential}`;
};

// Static method to generate verification code
certificateSchema.statics.generateVerificationCode = async function() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 12; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }

  // Check if code already exists
  const existing = await this.findOne({ verificationCode: code });
  if (existing) {
    return this.generateVerificationCode();
  }

  return code;
};

// Instance method to verify certificate
certificateSchema.methods.verify = async function(verifiedBy) {
  this.isVerified = true;
  this.verifiedBy = verifiedBy;
  this.verifiedAt = new Date();
  this.status = 'VERIFIED';
  return this.save();
};

// Instance method to cancel certificate
certificateSchema.methods.cancel = async function(reason, cancelledBy) {
  this.status = 'CANCELLED';
  this.remarks = reason || this.remarks;
  this.updatedBy = cancelledBy;
  return this.save();
};

// Static method to verify by code
certificateSchema.statics.verifyByCode = async function(code) {
  return this.findOne({
    verificationCode: code,
    status: { $in: ['ISSUED', 'VERIFIED'] },
    isDeleted: { $ne: true }
  }).populate('studentId', 'name admissionNumber');
};

module.exports = mongoose.model('Certificate', certificateSchema);
